services:
  db:
    image: mysql:8.0
    container_name: mast_db
    restart: always
    environment:
      MYSQL_DATABASE: mast_db
      MYSQL_ROOT_PASSWORD: tfgnacho
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: mast_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app  # Allows code changes to be reflected instantly
      - ./uploads:/uploads

  files_server:
    image: nginx:alpine
    container_name: mast_files
    ports:
      - "8010:80" 
    volumes:
      - ./uploads:/usr/share/nginx/html:ro

volumes:
  db_data: